### ISSUE TITLE
DateTime change to Time

### ISSUE THREAD

**Issue by rwojnarowski** [Quintasan/woodpecker#1]
[Apply Rubocop fixes](https://github.com/Quintasan/woodpecker/commit/f981f51d4a8e2ece8d3a2cc69f362aecdaa975c7#diff-320771a1ba33f3892ed1088e54ff995cL11) - I think that this change caused some regression. I can't return campaign list. See the screenshot below:

![console](https://i.imgur.com/VpnLYgA.png)

**Comment by Quintasan** [comment]
@rwojnarowski Sorry for the late response. It appears that DateTime in Ruby works incorrectly as far as ISO8601 is concerned. Combined date and time in UTC would be `2018-05-06T12:53:22+00:00`. What I get from Woodpecker's API is `2018-05-17T12:17:11+0200` (note the missing colon in time zone).

The fact that this was working using `DateTime` is a bug in Ruby itself. I can either patch the library to use `#parse` or see if we can have the API return a proper ISO8601 string.

EDIT: Actually scratch that, it's a bug in `Time` - https://bugs.ruby-lang.org/issues/14790

**Comment by Quintasan** [comment]
@rwojnarowski Fixed in v0.1.4. Please check it out and reopen this issue if this still happens.
